### ISSUE TITLE
Bug if number of rows is a multiple of 10,000

### ISSUE THREAD

**Issue by jenny-cobbett** [jlolling/talendcomp_tGoogleAnalyticsInput#10]
Hi Jan!

This component is great :)

However, I am having an issue, where if the number of rows returned by the API is an exact multiple of 10,000; the component gets stuck in a loop and just keeps pulling the same rows of data over and over again (until eventually I go over the daily profile limit!)

I have the latest version (8.10) downloaded and have tried with both API 3 and 4, and changing various settings, but can't find a way around it.

Thanks so much
Jenny

**Comment by jlolling** [comment]
OK I will asap takle care of it.

**Comment by jlolling** [comment]
The number 10,000 comes from the fetch size. Could you please in the first place lower the number to let say 9000 to overcome the issues with job - of course only as workaround.

**Comment by jlolling** [comment]
I am not sure about that. Actually I think 10000 is also a limit in the API and cause some problems. I am digging in the source code to find the root cause. Unfortunately I do not have an account and web property which is frequently visited to have such amount of data for testing.

**Comment by jenny-cobbett** [comment]
Hi Jan, have given you read only access to our profile; this is the query I had an issue with as it's exactly 30,000 rows:
https://ga-dev-tools.appspot.com/query-explorer/?ids=ga%3A110043131&start-date=2021-04-04&end-date=2021-04-04&metrics=ga%3Apageviews&dimensions=ga%3ApagePath%2Cga%3Ahour%2Cga%3AcontentGroup1&filters=ga%3Apageviews%3E0%3Bga%3Ahour%3D%3D00%2Cga%3Ahour%3D%3D01%2Cga%3Ahour%3D%3D02%3Bga%3Acontentgroup1%3D%3DThread%20Pages%2Cga%3Acontentgroup1%3D%3DContent%20(CMS)%20Pages%2Cga%3Acontentgroup1%3D%3DNew%20Content%20Pages%2Cga%3Acontentgroup1%3D%3DWiki%20Pages

**Comment by jlolling** [comment]
Thats very kind of you. I have tested it on my side and in my job it does not stuck. It stops exactly at 30000 rows and do not repeat of stuck in a loop. Could we have a zoom session?

**Comment by jenny-cobbett** [comment]
Hi Jan, thanks so much for helping! I can do a zoom session, when is good for you?

**Comment by jlolling** [comment]
What about now?

**Comment by jenny-cobbett** [comment]
Hi Jan, I think I have sent you a meeting invite to your gmail

**Comment by jlolling** [comment]
Hi Jenny, I can reproduce this now on my own account by setting the max rows exactly as the number of rows returned by my query. It is definitely related to the Version 4 implementation.

**Comment by jlolling** [comment]
Hi Jenny, I have found the root cause and solved it. I am going to publish as new release today.
Thanks a lot for notifying me about that problem and providing a test account. You can now remove me from your account.
Best regards
Jan Lolling

**Comment by jlolling** [comment]
I have just release the version 8.11. Here the link to Talend Exchange: https://exchange.talend.com/#marketplaceproductoverview:marketplace=marketplace%252F1&p=marketplace%252F1%252Fproducts%252F546&pi=marketplace%252F1%252Fproducts%252F546%252Fitems%252F2984

**Comment by jenny-cobbett** [comment]
Thanks Jan, this works now! I have removed your access. Thanks for sorting this so super speedily.

**Comment by jlolling** [comment]
Happy to help. 
Best regards
Jan
