### ISSUE TITLE
Support of DynamicSchema

### ISSUE THREAD

**Issue by ucas-stu** [jlolling/talendcomp_tGoogleAnalyticsInput#21]
This is not supported and would allow the component to generic in that it could be fed it's input args from globalMap or context parameters and the response flow would be of (at least) the correct column numerity even if just set to String dataType.

Context:
I am moving a large number of jobs from Matillion to Talend (over 200). They all have the same characteristics: The target table has the same number of columns as the number of metrics and dimensions. Thus, I can (through querying the GA Metadata) validate and determine the datatypes of each and create a table (based on the given view id) to receive result data. 

The tGoogleAnalyticsInput is also being fed the same list of metrics and dimensions, but there is no way to tell the component to produce a schema based of Dynamic.

**Comment by jlolling** [comment]
This component works also for Open Studio and here we do not have the Dynamic type. To enable it I had to steal code from Talend and reengineer the Dynamic type classes.

**Comment by ucas-stu** [comment]
Right! I understand the context for which it was written now. 

At the moment I don't have the luxury of rewriting the schema - that's an event horizon we've not yet come to. So I am stuck with the 1 GA Query result set to 1 Table mapping. The business problem I am facing is the sheer number of reports which I don't have access to - thus constraining me to the existing database schema.

*thought*
I'm now wondering if I received normalized data - I could process them into a dynamic schema through downstream components and do the mapping that way: I'll take a look.

Would love to hear your thoughts.

**Comment by jlolling** [comment]
If the reports have the same number of dimensions and metrics than you can use generic schema names like dim1, dim2n metric1, metric2, etc….

**Comment by ucas-stu** [comment]
Just want to say thanks!
I've now successfully use the normalised data flows and through generating SQL as a crosstab query able to dynamically generate any version of the data I need.
