### ISSUE TITLE
Duplicate local variable warningAboutSchemaMismatchDone

### ISSUE THREAD

**Issue by jgillmanjr** [jlolling/talendcomp_tGoogleAnalyticsInput#3]
Hello!

Unless I'm missing something, it appears that I can only use a single segment for each tGoogleAnalyticsInput component.

So in an attempt for a quick work around, I was planning on using two instances of the component and then connecting them to a tUnite component, each one having the different segment IDs.

![selection_688](https://user-images.githubusercontent.com/3164015/38831387-3142b5fa-418d-11e8-9f8a-34fc56edd188.png)

However, when running the job, I get the following error:
`Detail Message: Duplicate local variable warningAboutSchemaMismatchDone`

I'm not a Java developer by any stretch, but I'm guessing this is probably better served as a property of the object representing the instances of tGoogleAnalyticsInput?

**Comment by jlolling** [comment]
Hi, sorry, this is an error and I have to fix that. 
But you can avoid this:
Please change your job design a bit:
tGoogleAnalyticsInput_1 --> tHashOutput_1
OnSubjobOk
tGoogleAnalyticsInput_2 --> tHashOutput_2
OnSubSubjobOk
tHashInput_1 -->
tHashInput_2 --> tUnit_1-->tSortRow_1-->tLogRow_1

This design prevents the problem.

**Comment by jlolling** [comment]
I have taken a look into my component and I am pretty convinced your problem is actually already solved. Could you please check the version of the component in the advanced settings of the component? I guess you are working with an old version.

**Comment by jgillmanjr** [comment]
Your work around worked beautifully! Thank you for the quick response!!

As for the release:
`Release: 8.4 build at: 20170603`

I acquired this version by way of the Talend Exchange.

If by chance you happen to be at TalendConnect in May, please let me know. I'd be more than happy to buy you a beer. I've also been using your `tGoogleAdWordsReport` component and that has been working great for us as well!

-Jason

**Comment by jgillmanjr** [comment]
I figured the hop across the pond might have been a bit much for a two day conference, but I figure I'd ask :)

Of course, I just *now* noticed commit 7f3bdb31d8d63176e52e18a80a105bd37e828c71 which seems to address the issue that I mentioned.

Not sure how hard it is to release a new version to the exchange, but I'll definitely be keeping an eye out for it!

-Jason

**Comment by jlolling** [comment]
Actually I had a new release already in production for my customers. I simply forgot to publish it here and in Talend Exchange. I have done this now.
