### ISSUE TITLE
Socket Timeout when trying to connect via OAuth

### ISSUE THREAD

**Issue by NilsKaper** [jlolling/talendcomp_tGoogleAnalyticsInput#5]
Hello,
I'm successfully authenticating my account via browser. 
But afterwards, the process in Talend always fails giving me a SocketTimeoutException.
Any help?

Sincerely,
Nils Kaper

**Comment by jlolling** [comment]
In your Browser you perhapse use proxy settings which unknown for your job.
Please check if you need proxy settings and apply them with the componen
tSetProxy in your job.

Best regards
Jan

NilsKaper <notifications@github.com> schrieb am Do., 20. Feb. 2020, 10:15:
